-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "legacyTotalAmount" DOUBLE PRECISION,
ADD COLUMN     "netAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 22;
