import { statistiche } from '../src/lib/statistiche'
import { db } from '../src/lib/db'
const t0 = Date.now()
const s = await statistiche(30)
console.log(`calcolate in ${Date.now() - t0} ms\n`)
console.log('ORDINI  ', s.ordini.totale, '· venduto', s.ordini.venduto, '· scontrino', s.ordini.scontrinoMedio)
console.log('  marchi:', s.ordini.perMarchio.map((m) => `${m.nome} ${m.quanti}`).join(' · '))
console.log('  stati :', s.ordini.perStato.map((m) => `${m.stato} ${m.quanti}`).join(' · '))
console.log('  gestione: mediana', s.ordini.tempoDiGestione.mediana, 'min · media', s.ordini.tempoDiGestione.media, `su ${s.ordini.tempoDiGestione.casi} ordini`)
console.log('  gestiti', JSON.stringify(s.ordini.gestiti), '· in app', JSON.stringify(s.ordini.inApp))
console.log('SERVIZIO conversazioni', s.servizio.conversazioni, '· in', s.servizio.messaggiRicevuti, '· out', s.servizio.messaggiInviati)
console.log('  risposta: mediana', s.servizio.tempoDiRisposta.mediana, 'min · media', s.servizio.tempoDiRisposta.media, `su ${s.servizio.tempoDiRisposta.casi}`)
console.log('  senza risposta', JSON.stringify(s.servizio.senzaRisposta))
console.log('  chiamate', s.servizio.chiamate, '· senza ordine', JSON.stringify(s.servizio.chiamateSenzaOrdine))
console.log('QUALITA reclami', JSON.stringify(s.qualita.reclami), '· gravi', JSON.stringify(s.qualita.reclamiGravi))
console.log('  rimborsi', s.qualita.rimborsiChiesti, 'chiesti ·', s.qualita.rimborsiEseguiti, 'eseguiti ·', s.qualita.rimborsatoEuro, 'EUR ·', JSON.stringify(s.qualita.rimborsatoSuVenduto))
console.log('SOLDI richieste', s.soldi.richiestePagamento, JSON.stringify(s.soldi.richiestePagate), '· tempo pagamento mediana', s.soldi.tempoDiPagamento.mediana)
console.log('  preventivi', s.soldi.preventivi, JSON.stringify(s.soldi.preventiviInviati))
console.log('\nAVVERTENZE:'); for (const x of s.avvertenze) console.log(' ·', x)
await db.$disconnect()
