/**
 * Deluxy Fondo — cambi di amministratore delegato degli ultimi 24 mesi.
 *
 * FILE GENERATO da scripts/genera-universo.mjs: non modificarlo a mano, si perde al giro
 * successivo. Per cambiare i dati si modifica lo script.
 *
 * Ogni ticker è stato provato davvero sull'API dei prezzi prima di entrare qui. Sono
 * esclusi di proposito:
 *  - i casi in cui il predecessore è uscito ma NESSUN successore è stato nominato
 *    (Ferragamo, The Italian Sea Group): un mandato che non è cominciato non si misura;
 *  - Telefónica (TEF.MC): la fonte prezzi non ha storico (109 sedute anche con range=max),
 *    quindi il mandato non è misurabile e il titolo non entra nell'universo;
 *  - i titoli delistati o incorporati (Anima, illimity, Banca Popolare di Sondrio, Tod's):
 *    la serie dei prezzi si ferma e ogni confronto con l'indice diventa falso;
 *  - i casi dove cambia solo la presidenza o si accorpano deleghe su chi già comandava
 *    (Lottomatica, MFE, Unipol, De' Longhi): non sono cambi di gestione.
 *
 * Un caso limite degno di nota è MPS: nel marzo 2026 l'amministratore delegato è stato
 * revocato e licenziato per giusta causa, poi reintegrato dall'assemblea in aprile. Cambio
 * annunciato e mai avvenuto: resta fuori, perché non esiste un mandato nuovo da misurare.
 */

import type { EventoManagement } from "./tipi";
import type { Titolo } from "./universo.ts";

export const TITOLI_RECENTI: Titolo[] = [
  {
    simbolo: "TRN.MI",
    nome: "Terna",
    paese: "Italia",
    settore: "Utility, reti elettriche",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-04-09.",
  },
  {
    simbolo: "ENAV.MI",
    nome: "ENAV",
    paese: "Italia",
    settore: "Infrastrutture, controllo del traffico aereo",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-04-09.",
  },
  {
    simbolo: "CPR.MI",
    nome: "Davide Campari-Milano",
    paese: "Italia / Paesi Bassi",
    settore: "Bevande e distillati",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2024-12-04.",
  },
  {
    simbolo: "MB.MI",
    nome: "Mediobanca",
    paese: "Italia",
    settore: "Banche e investment banking",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-10-28.",
  },
  {
    simbolo: "NEXI.MI",
    nome: "Nexi",
    paese: "Italia",
    settore: "Pagamenti digitali",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-03-25.",
  },
  {
    simbolo: "MONC.MI",
    nome: "Moncler",
    paese: "Italia",
    settore: "Lusso e abbigliamento",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-01-20.",
  },
  {
    simbolo: "GEO.MI",
    nome: "Geox",
    paese: "Italia",
    settore: "Calzature",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-07-23.",
  },
  {
    simbolo: "IRE.MI",
    nome: "Iren",
    paese: "Italia",
    settore: "Multiutility",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2024-09-10.",
  },
  {
    simbolo: "SRG.MI",
    nome: "Snam",
    paese: "Italia",
    settore: "Infrastrutture del gas",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-05-14.",
  },
  {
    simbolo: "TEN.MI",
    nome: "Tenaris",
    paese: "Italia / Lussemburgo",
    settore: "Tubi per l'energia",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-05-06.",
  },
  {
    simbolo: "BFF.MI",
    nome: "BFF Bank",
    paese: "Italia",
    settore: "Banca specializzata",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-03-18.",
  },
  {
    simbolo: "PRT.MI",
    nome: "Esprinet",
    paese: "Italia",
    settore: "Distribuzione informatica",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-03-12.",
  },
  {
    simbolo: "ASC.MI",
    nome: "Ascopiave",
    paese: "Italia",
    settore: "Distribuzione del gas",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-06-08.",
  },
  {
    simbolo: "JUVE.MI",
    nome: "Juventus Football Club",
    paese: "Italia",
    settore: "Sport e intrattenimento",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-11-11.",
  },
  {
    simbolo: "ELC.MI",
    nome: "Elica",
    paese: "Italia",
    settore: "Elettrodomestici",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-03-25.",
  },
  {
    simbolo: "BSS.MI",
    nome: "Biesse",
    paese: "Italia",
    settore: "Macchine utensili",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-06-12.",
  },
  {
    simbolo: "KER.PA",
    nome: "Kering",
    paese: "Francia",
    settore: "Lusso",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-06-16.",
  },
  {
    simbolo: "RNO.PA",
    nome: "Renault",
    paese: "Francia",
    settore: "Automotive",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-07-31.",
  },
  {
    simbolo: "ULVR.L",
    nome: "Unilever",
    paese: "Regno Unito",
    settore: "Beni di consumo",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-02-25.",
  },
  {
    simbolo: "DGE.L",
    nome: "Diageo",
    paese: "Regno Unito",
    settore: "Bevande e distillati",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-11-10.",
  },
  {
    simbolo: "PUM.DE",
    nome: "Puma",
    paese: "Germania",
    settore: "Abbigliamento sportivo",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-04-03.",
  },
  {
    simbolo: "CBK.DE",
    nome: "Commerzbank",
    paese: "Germania",
    settore: "Banche",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2024-09-24.",
  },
  {
    simbolo: "P911.DE",
    nome: "Porsche AG",
    paese: "Germania",
    settore: "Automotive di lusso",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-10-17.",
  },
  {
    simbolo: "NOVO-B.CO",
    nome: "Novo Nordisk",
    paese: "Danimarca",
    settore: "Farmaceutico",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-07-29.",
  },
  {
    simbolo: "ATO.PA",
    nome: "Atos",
    paese: "Francia",
    settore: "Servizi informatici",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2024-10-14.",
  },
  {
    simbolo: "WLN.PA",
    nome: "Worldline",
    paese: "Francia",
    settore: "Pagamenti",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-02-25.",
  },
  {
    simbolo: "ALO.PA",
    nome: "Alstom",
    paese: "Francia",
    settore: "Ferroviario",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-10-08.",
  },
  {
    simbolo: "BP.L",
    nome: "BP",
    paese: "Regno Unito",
    settore: "Petrolio e gas",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-12-18.",
  },
  {
    simbolo: "BMW.DE",
    nome: "BMW",
    paese: "Germania",
    settore: "Automotive",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-12-09.",
  },
  {
    simbolo: "MRK.DE",
    nome: "Merck KGaA",
    paese: "Germania",
    settore: "Farmaceutico e scienze della vita",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-09-25.",
  },
  {
    simbolo: "VNA.DE",
    nome: "Vonovia",
    paese: "Germania",
    settore: "Immobiliare residenziale",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-05-06.",
  },
  {
    simbolo: "NESN.SW",
    nome: "Nestlé",
    paese: "Svizzera",
    settore: "Alimentare",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-09-01.",
  },
  {
    simbolo: "INTC",
    nome: "Intel",
    paese: "Stati Uniti",
    settore: "Semiconduttori",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2025-03-12.",
  },
  {
    simbolo: "NKE",
    nome: "Nike",
    paese: "Stati Uniti",
    settore: "Abbigliamento sportivo",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2024-09-19.",
  },
  {
    simbolo: "AAPL",
    nome: "Apple",
    paese: "Stati Uniti",
    settore: "Tecnologia",
    isin: null,
    ruolo: "recente",
    benchmark: "FTSEMIB.MI",
    note: "Cambio di amministratore delegato annunciato il 2026-04-20.",
  },
];

export const EVENTI_RECENTI: EventoManagement[] = [
  {
    id: "trn-monti-in",
    categoria: "management",
    simbolo: "TRN.MI",
    dataRumor: null,
    dataAnnuncio: "2026-04-09",
    dataEfficacia: "2026-05-12",
    tier: "T2",
    titolo: "Pasqualino Monti amministratore delegato di Terna",
    persona: "Pasqualino Monti",
    predecessore: "Giuseppina Di Foggia",
    descrizione: "Di Foggia non riconfermata nel giro di nomine delle partecipate pubbliche; Monti arriva dalla guida di ENAV.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Terna — insediamento del nuovo consiglio", url: "https://www.terna.it/it/media/comunicati-stampa/dettaglio/insediamento-nuovo-consiglio-amministrazione-2026", data: "2026-05-12" }],
  },
  {
    id: "enav-biasio-in",
    categoria: "management",
    simbolo: "ENAV.MI",
    dataRumor: null,
    dataAnnuncio: "2026-04-09",
    dataEfficacia: "2026-05-14",
    tier: "T2",
    titolo: "Igor De Biasio amministratore delegato di ENAV",
    persona: "Igor De Biasio",
    predecessore: "Pasqualino Monti",
    descrizione: "Effetto domino delle nomine pubbliche: Monti passa a Terna, al suo posto De Biasio, già presidente di Terna.",
    forzato: false,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "ENAV — nomina dell'amministratore delegato", url: "https://www.enav.it/node/18617", data: "2026-05-14" }],
  },
  {
    id: "cpr-hunt-in",
    categoria: "management",
    simbolo: "CPR.MI",
    dataRumor: null,
    dataAnnuncio: "2024-12-04",
    dataEfficacia: "2025-01-15",
    tier: "T2",
    titolo: "Simon Hunt amministratore delegato di Davide Campari-Milano",
    persona: "Simon Hunt",
    predecessore: "Matteo Fantacchiotti",
    descrizione: "Fantacchiotti si dimette dopo cinque mesi in piena frenata del settore; dopo una reggenza ad interim arriva Hunt dall'esterno.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Campari — dimissioni dell'amministratore delegato", url: "https://www.camparigroup.com/sites/default/files/downloads/20240918_CEO%20Resignation.pdf", data: "2024-09-18" }],
  },
  {
    id: "mb-deril-in",
    categoria: "management",
    simbolo: "MB.MI",
    dataRumor: null,
    dataAnnuncio: "2025-10-28",
    dataEfficacia: "2025-10-28",
    tier: "T2",
    titolo: "Alessandro Melzi d'Eril amministratore delegato di Mediobanca",
    persona: "Alessandro Melzi d'Eril",
    predecessore: "Alberto Nagel",
    descrizione: "Nagel si dimette dopo il successo dell'offerta di MPS; il nuovo consiglio nomina Melzi d'Eril, che arriva da Anima.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "media",
    fonti: [{ titolo: "Mediobanca, il nuovo amministratore delegato", url: "https://www.insurancetrade.it/insurance/contenuti/mercato/15768/mediobanca-melzi-d-eril-e-il-nuovo-amministratore-delegato", data: "2025-10-28" }],
  },
  {
    id: "nexi-mingrone-in",
    categoria: "management",
    simbolo: "NEXI.MI",
    dataRumor: null,
    dataAnnuncio: "2026-03-25",
    dataEfficacia: "2026-03-25",
    tier: "T3",
    titolo: "Bernardo Mingrone amministratore delegato di Nexi",
    persona: "Bernardo Mingrone",
    predecessore: "Paolo Bertoluzzo",
    descrizione: "Sostituzione spinta dagli azionisti di riferimento dopo la bocciatura del piano industriale e un titolo a -40% in un anno.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Nexi, Mingrone nuovo amministratore delegato", url: "https://www.borsaitaliana.it/borsa/notizie/teleborsa/finanza/nexi-bernardo-mingrone-nuovo-ceo-paolo-bertoluzzo-lascia-dopo-10-anni-11_2026-03-26_TLB.html", data: "2026-03-26" }],
  },
  {
    id: "monc-rongone-in",
    categoria: "management",
    simbolo: "MONC.MI",
    dataRumor: null,
    dataAnnuncio: "2026-01-20",
    dataEfficacia: "2026-04-01",
    tier: "T2",
    titolo: "Bartolomeo Rongone amministratore delegato di Moncler",
    persona: "Bartolomeo Rongone",
    predecessore: "Remo Ruffini",
    descrizione: "Separazione fra proprietà e gestione: Ruffini resta presidente esecutivo, la gestione va a un manager esterno di primo piano.",
    forzato: false,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Moncler nomina Rongone amministratore delegato", url: "https://www.borsaitaliana.it/borsa/notizie/teleborsa/finanza/moncler-nomina-bartolomeo-rongone-nuovo-ceo-remo-ruffini-assume-il-ruolo-di-presidente-esecutivo-197_2026-01-20_TLB.html", data: "2026-01-20" }],
  },
  {
    id: "geo-giovanni-in",
    categoria: "management",
    simbolo: "GEO.MI",
    dataRumor: null,
    dataAnnuncio: "2025-07-23",
    dataEfficacia: "2025-07-23",
    tier: "T2",
    titolo: "Francesco Di Giovanni amministratore delegato di Geox",
    persona: "Francesco Di Giovanni",
    predecessore: "Enrico Mistron",
    descrizione: "Seconda sostituzione del vertice in sedici mesi, per accelerare il rilancio e il taglio dei costi.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Geox, il nuovo amministratore delegato", url: "https://www.milanofinanza.it/fashion/geox-francesco-di-giovanni-e-il-nuovo-amministratore-delegato-al-via-la-fase-due-del-rilancio-202507231851419743", data: "2025-07-23" }],
  },
  {
    id: "ire-bufo-in",
    categoria: "management",
    simbolo: "IRE.MI",
    dataRumor: null,
    dataAnnuncio: "2024-09-10",
    dataEfficacia: "2024-09-10",
    tier: "T3",
    titolo: "Gianluca Bufo amministratore delegato di Iren",
    persona: "Gianluca Bufo",
    predecessore: "Paolo Signorini",
    descrizione: "Nomina dopo mesi senza amministratore delegato: il predecessore era stato arrestato e revocato per giusta causa.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Iren nomina Gianluca Bufo", url: "https://www.gruppoiren.it/it/media/comunicati-stampa/2024/il-consiglio-di-amministrazione-di-Iren-nomina-Gianluca-Bufo-Amministratore-delegato-e-direttore-generale.html", data: "2024-09-10" }],
  },
  {
    id: "srg-scornajenchi-in",
    categoria: "management",
    simbolo: "SRG.MI",
    dataRumor: null,
    dataAnnuncio: "2025-05-14",
    dataEfficacia: "2025-05-14",
    tier: "T2",
    titolo: "Agostino Scornajenchi amministratore delegato di Snam",
    persona: "Agostino Scornajenchi",
    predecessore: "Stefano Venier",
    descrizione: "Venier dato per la riconferma ma non inserito nella lista dell'azionista pubblico.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "media",
    fonti: [{ titolo: "Snam, Scornajenchi nuovo amministratore delegato", url: "https://www.ansa.it/sito/notizie/economia/2025/05/14/snam-agostino-scornajenchi-nuovo-amministratore-delegato_84ca86dc-392b-494c-9076-31a95483e962.html", data: "2025-05-14" }],
  },
  {
    id: "ten-podskubka-in",
    categoria: "management",
    simbolo: "TEN.MI",
    dataRumor: null,
    dataAnnuncio: "2026-05-06",
    dataEfficacia: null,
    tier: "T3",
    titolo: "Gabriel Podskubka amministratore delegato di Tenaris",
    persona: "Gabriel Podskubka",
    predecessore: "Paolo Rocca",
    descrizione: "Successione pianificata dopo 25 anni: Rocca resta presidente, il vertice operativo passa a un interno.",
    forzato: false,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Tenaris announces CEO succession", url: "https://www.tenaris.com/en/news/2026/tenaris-announces-ceo-succession", data: "2026-05-06" }],
  },
  {
    id: "bff-sica-in",
    categoria: "management",
    simbolo: "BFF.MI",
    dataRumor: null,
    dataAnnuncio: "2026-03-18",
    dataEfficacia: "2026-03-18",
    tier: "T3",
    titolo: "Giuseppe Sica amministratore delegato di BFF Bank",
    persona: "Giuseppe Sica",
    predecessore: "Massimiliano Belingheri",
    descrizione: "Uscita contestuale alla rettifica dei conti passati, al taglio del target e a un titolo in caduta di circa il 30%.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "BFF Bank, Sica nuovo amministratore delegato", url: "https://www.bebankers.it/bff-bank-giuseppe-sica-nuovo-amministratore-delegato/", data: "2026-03-18" }],
  },
  {
    id: "prt-testa-in",
    categoria: "management",
    simbolo: "PRT.MI",
    dataRumor: null,
    dataAnnuncio: "2026-03-12",
    dataEfficacia: "2026-05-01",
    tier: "T3",
    titolo: "Giovanni Testa amministratore delegato di Esprinet",
    persona: "Giovanni Testa",
    predecessore: "Alessandro Cattani",
    descrizione: "Successione pianificata dopo oltre venticinque anni; il predecessore resta azionista rilevante.",
    forzato: false,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Esprinet, Testa nuovo amministratore delegato", url: "https://www.channelcity.it/news/30109/esprinet-giovanni-testa-e-il-nuovo-amministratore-delegato.html", data: "2026-03-23" }],
  },
  {
    id: "asc-fae-in",
    categoria: "management",
    simbolo: "ASC.MI",
    dataRumor: null,
    dataAnnuncio: "2026-06-08",
    dataEfficacia: "2026-06-08",
    tier: "T3",
    titolo: "Stefano Faè amministratore delegato di Ascopiave",
    persona: "Stefano Faè",
    predecessore: "Nicola Cecconato",
    descrizione: "Mancato rinnovo del predecessore in assemblea e uscita consensuale; poteri accentrati sull'amministratore delegato.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "media",
    fonti: [{ titolo: "Ascopiave, nominato il nuovo amministratore delegato", url: "https://www.quotidianoenergia.it/module/news/page/entry/id/532889", data: "2026-06-08" }],
  },
  {
    id: "juve-comolli-in",
    categoria: "management",
    simbolo: "JUVE.MI",
    dataRumor: null,
    dataAnnuncio: "2025-11-11",
    dataEfficacia: "2025-11-11",
    tier: "T3",
    titolo: "Damien Comolli amministratore delegato di Juventus Football Club",
    persona: "Damien Comolli",
    predecessore: "Maurizio Scanavino",
    descrizione: "Cessato il mandato del predecessore, il consiglio promuove il direttore generale in carica dall'estate.",
    forzato: null,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Juventus — Comolli nominato amministratore delegato", url: "https://www.juventus.com/it/news/articoli/damien-comolli-nominato-amministratore-delegato-11-11-2025", data: "2025-11-11" }],
  },
  {
    id: "elc-barboni-in",
    categoria: "management",
    simbolo: "ELC.MI",
    dataRumor: null,
    dataAnnuncio: "2026-03-25",
    dataEfficacia: "2026-03-25",
    tier: "T3",
    titolo: "Luca Barboni amministratore delegato di Elica",
    persona: "Luca Barboni",
    predecessore: "Giulio Cocci",
    descrizione: "Ricambio concordato dopo un esercizio chiuso in perdita, con semplificazione della struttura manageriale; il successore è in azienda da oltre vent'anni.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Elica, Barboni nuovo amministratore delegato", url: "https://www.borsaitaliana.it/borsa/notizie/teleborsa/finanza/elica-luca-barboni-nuovo-ceo-giulio-cocci-si-dimette-in-accordo-con-la-societa-111_2026-03-25_TLB.html", data: "2026-03-25" }],
  },
  {
    id: "bss-selci-in",
    categoria: "management",
    simbolo: "BSS.MI",
    dataRumor: null,
    dataAnnuncio: "2025-06-12",
    dataEfficacia: "2025-06-12",
    tier: "T3",
    titolo: "Roberto Selci amministratore delegato di Biesse",
    persona: "Roberto Selci",
    predecessore: "Massimo Potenza",
    descrizione: "Ritorno della famiglia fondatrice alla guida operativa dopo il tentativo con un manager esterno; uscita accompagnata da una indennità rilevante.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "media",
    fonti: [{ titolo: "Biesse, Selci nuovo amministratore delegato", url: "https://www.teleborsa.it/News/2025/06/12/biesse-potenza-rinuncia-alla-carica-di-ceo-e-direttore-generale-selci-nuovo-ad-81.html", data: "2025-06-12" }],
  },
  {
    id: "ker-meo-in",
    categoria: "management",
    simbolo: "KER.PA",
    dataRumor: null,
    dataAnnuncio: "2025-06-16",
    dataEfficacia: "2025-09-15",
    tier: "T2",
    titolo: "Luca de Meo amministratore delegato di Kering",
    persona: "Luca de Meo",
    predecessore: "François-Henri Pinault",
    descrizione: "Separazione dei ruoli di presidente e amministratore delegato; de Meo arriva da Renault per rilanciare il marchio principale.",
    forzato: false,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Kering announces the appointment of Luca de Meo", url: "https://www.globenewswire.com/news-release/2025/06/16/3100070/0/en/Kering-announces-the-appointment-of-Luca-de-Meo-as-Chief-Executive-Officer.html", data: "2025-06-16" }],
  },
  {
    id: "rno-provost-in",
    categoria: "management",
    simbolo: "RNO.PA",
    dataRumor: null,
    dataAnnuncio: "2025-07-31",
    dataEfficacia: "2025-07-31",
    tier: "T3",
    titolo: "François Provost amministratore delegato di Renault",
    persona: "François Provost",
    predecessore: "Luca de Meo",
    descrizione: "Uscita improvvisa del predecessore verso un altro gruppo; scelta interna per non cambiare rotta.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "media",
    fonti: [{ titolo: "Provost appointed new CEO of Renault Group", url: "https://www.electrive.com/2025/07/31/francois-provost-appointed-new-ceo-of-renault-group/", data: "2025-07-31" }],
  },
  {
    id: "ulvr-fernandez-in",
    categoria: "management",
    simbolo: "ULVR.L",
    dataRumor: null,
    dataAnnuncio: "2025-02-25",
    dataEfficacia: "2025-03-01",
    tier: "T3",
    titolo: "Fernando Fernandez amministratore delegato di Unilever",
    persona: "Fernando Fernandez",
    predecessore: "Hein Schumacher",
    descrizione: "Uscita dopo meno di due anni: il consiglio non era soddisfatto del ritmo della ristrutturazione, con un attivista nel capitale.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Unilever Board update", url: "https://www.unilever.com/news/press-and-media/press-releases/2025/unilever-board-update-25-02-25/", data: "2025-02-25" }],
  },
  {
    id: "dge-lewis-in",
    categoria: "management",
    simbolo: "DGE.L",
    dataRumor: null,
    dataAnnuncio: "2025-11-10",
    dataEfficacia: "2026-01-01",
    tier: "T2",
    titolo: "Dave Lewis amministratore delegato di Diageo",
    persona: "Dave Lewis",
    predecessore: "Debra Crew",
    descrizione: "Uscita per mutuo accordo dopo il crollo del titolo; arriva un esterno con un passato da amministratore delegato nella grande distribuzione.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Sir Dave Lewis appointed Diageo CEO", url: "https://www.diageo.com/en/news-and-media/press-releases/2025/sir-dave-lewis-appointed-diageo-plc-ceo", data: "2025-11-10" }],
  },
  {
    id: "pum-hoeld-in",
    categoria: "management",
    simbolo: "PUM.DE",
    dataRumor: null,
    dataAnnuncio: "2025-04-03",
    dataEfficacia: "2025-07-01",
    tier: "T2",
    titolo: "Arthur Hoeld amministratore delegato di Puma",
    persona: "Arthur Hoeld",
    predecessore: "Arne Freundt",
    descrizione: "Uscita per visioni divergenti sull'esecuzione della strategia dopo trimestri deludenti; il successore arriva dal concorrente principale.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "PUMA appoints Arthur Hoeld as CEO", url: "https://about.puma.com/en/newsroom/corporate-news/2025/03-04-2025-puma-appoints-arthur-hoeld-ceo-and-matthias-baumer-chief", data: "2025-04-03" }],
  },
  {
    id: "cbk-orlopp-in",
    categoria: "management",
    simbolo: "CBK.DE",
    dataRumor: null,
    dataAnnuncio: "2024-09-24",
    dataEfficacia: "2024-10-01",
    tier: "T3",
    titolo: "Bettina Orlopp amministratore delegato di Commerzbank",
    persona: "Bettina Orlopp",
    predecessore: "Manfred Knof",
    descrizione: "Uscita anticipata di oltre un anno mentre un concorrente saliva nel capitale; promossa la responsabile finanziaria.",
    forzato: null,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Commerzbank — Wechsel an der Konzernspitze", url: "https://www.commerzbank.de/group/newsroom/press-releases/2024/20240924-pm-wechsel-konzernspitze.pdf", data: "2024-09-24" }],
  },
  {
    id: "p911-leiters-in",
    categoria: "management",
    simbolo: "P911.DE",
    dataRumor: null,
    dataAnnuncio: "2025-10-17",
    dataEfficacia: "2026-01-01",
    tier: "T2",
    titolo: "Michael Leiters amministratore delegato di Porsche AG",
    persona: "Michael Leiters",
    predecessore: "Oliver Blume",
    descrizione: "Fine del doppio incarico del predecessore dopo la costosa marcia indietro sull'elettrico.",
    forzato: null,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Leiters becomes CEO of Porsche AG", url: "https://newsroom.porsche.com/en/2025/company/porsche-dr-michael-leiters-becomes-ceo-on-1-january-2026-40864.html", data: "2025-10-17" }],
  },
  {
    id: "novo-b-doustdar-in",
    categoria: "management",
    simbolo: "NOVO-B.CO",
    dataRumor: null,
    dataAnnuncio: "2025-07-29",
    dataEfficacia: "2025-08-07",
    tier: "T3",
    titolo: "Maziar Mike Doustdar amministratore delegato di Novo Nordisk",
    persona: "Maziar Mike Doustdar",
    predecessore: "Lars Fruergaard Jørgensen",
    descrizione: "Uscita dopo il crollo del titolo e la perdita del vantaggio competitivo; annuncio contestuale al taglio della guidance.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Doustdar appointed CEO of Novo Nordisk", url: "https://www.novonordisk.com/content/nncorp/global/en/news-and-media/news-and-ir-materials/news-details.html?id=916408", data: "2025-07-29" }],
  },
  {
    id: "ato-salle-in",
    categoria: "management",
    simbolo: "ATO.PA",
    dataRumor: null,
    dataAnnuncio: "2024-10-14",
    dataEfficacia: "2025-02-01",
    tier: "T2",
    titolo: "Philippe Salle amministratore delegato di Atos",
    persona: "Philippe Salle",
    predecessore: "Jean-Pierre Mustier",
    descrizione: "Settimo amministratore delegato in tre anni; il successore investe di tasca propria nel capitale.",
    forzato: null,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Atos appoints Philippe Salle", url: "https://www.atosgroup.com/en/press/atos-appoints-philippe-salle-chairman-of-the-board-of-directors-with-effect-from-october-14-2024-and-chairman-and-chief-executive-officer-from-february-01-2025", data: "2024-10-14" }],
  },
  {
    id: "wln-vacheron-in",
    categoria: "management",
    simbolo: "WLN.PA",
    dataRumor: null,
    dataAnnuncio: "2025-02-25",
    dataEfficacia: "2025-03-01",
    tier: "T2",
    titolo: "Pierre-Antoine Vacheron amministratore delegato di Worldline",
    persona: "Pierre-Antoine Vacheron",
    predecessore: "Marc-Henri Desportes",
    descrizione: "Dopo i profit warning il consiglio giudica insufficiente anche la gestione ad interim e dichiara di volere un profilo esterno.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Worldline appoints Pierre-Antoine Vacheron", url: "https://investors.worldline.com/en/home/news-events/financial-press-releases/2025/pr-2025_02_25_01", data: "2025-02-25" }],
  },
  {
    id: "alo-sion-in",
    categoria: "management",
    simbolo: "ALO.PA",
    dataRumor: null,
    dataAnnuncio: "2025-10-08",
    dataEfficacia: "2026-04-01",
    tier: "T2",
    titolo: "Martin Sion amministratore delegato di Alstom",
    persona: "Martin Sion",
    predecessore: "Henri Poupart-Lafarge",
    descrizione: "Il predecessore annuncia di non voler chiedere un nuovo mandato dopo dieci anni; dopo mesi di ricerca arriva un esterno.",
    forzato: false,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Alstom appoints Martin Sion", url: "https://www.alstom.com/press-releases-news/2025/10/alstoms-board-directors-appoints-martin-sion-chief-executive-officer-effective-1-april-2026", data: "2025-10-08" }],
  },
  {
    id: "bp-oneill-in",
    categoria: "management",
    simbolo: "BP.L",
    dataRumor: null,
    dataAnnuncio: "2025-12-18",
    dataEfficacia: "2026-04-01",
    tier: "T2",
    titolo: "Meg O'Neill amministratore delegato di BP",
    persona: "Meg O'Neill",
    predecessore: "Murray Auchincloss",
    descrizione: "Uscita con effetto immediato dopo meno di due anni, sotto pressione degli attivisti; primo vertice esterno in 116 anni.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "bp announces leadership transition", url: "https://www.bp.com/en/global/corporate/news-and-insights/press-releases/bp-plc-announces-leadership-transition.html", data: "2025-12-18" }],
  },
  {
    id: "bmw-nedeljkovic-in",
    categoria: "management",
    simbolo: "BMW.DE",
    dataRumor: null,
    dataAnnuncio: "2025-12-09",
    dataEfficacia: "2026-05-14",
    tier: "T3",
    titolo: "Milan Nedeljković amministratore delegato di BMW",
    persona: "Milan Nedeljković",
    predecessore: "Oliver Zipse",
    descrizione: "Passaggio programmato a fine mandato; promosso il responsabile della produzione, con contratto lungo.",
    forzato: false,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "BMW — Nachfolge an der Vorstandsspitze", url: "https://www.press.bmwgroup.com/deutschland/article/detail/T0454373DE/", data: "2025-12-09" }],
  },
  {
    id: "mrk-beckmann-in",
    categoria: "management",
    simbolo: "MRK.DE",
    dataRumor: null,
    dataAnnuncio: "2025-09-25",
    dataEfficacia: "2026-05-01",
    tier: "T3",
    titolo: "Kai Beckmann amministratore delegato di Merck KGaA",
    persona: "Kai Beckmann",
    predecessore: "Belén Garijo",
    descrizione: "Passaggio di consegne programmato a fine mandato, con affiancamento preventivo del successore.",
    forzato: false,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Beckmann to succeed Garijo as CEO of Merck", url: "https://www.emdgroup.com/en/news/garijo-beckmann-25-09-25.html", data: "2025-09-25" }],
  },
  {
    id: "vna-mucic-in",
    categoria: "management",
    simbolo: "VNA.DE",
    dataRumor: null,
    dataAnnuncio: "2025-05-06",
    dataEfficacia: "2026-01-01",
    tier: "T2",
    titolo: "Luka Mucic amministratore delegato di Vonovia",
    persona: "Luka Mucic",
    predecessore: "Rolf Buch",
    descrizione: "Uscita dopo dodici anni e tre esercizi consecutivi in perdita; il successore arriva da un altro settore.",
    forzato: null,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Vonovia — Mucic appointed as new CEO", url: "https://www.vonovia.com/en/press/press-releases/2025/strong-start-to-the-year-and-optimistic-outlook-for-2025.-supervisory-board-decides-to-appoint-luka-mucic-as-new-ceo-to-succeed-rolf-buch", data: "2025-05-06" }],
  },
  {
    id: "nesn-navratil-in",
    categoria: "management",
    simbolo: "NESN.SW",
    dataRumor: null,
    dataAnnuncio: "2025-09-01",
    dataEfficacia: "2025-09-01",
    tier: "T3",
    titolo: "Philipp Navratil amministratore delegato di Nestlé",
    persona: "Philipp Navratil",
    predecessore: "Laurent Freixe",
    descrizione: "Predecessore licenziato con effetto immediato per violazione del codice di condotta; successore interno di lungo corso.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Nestlé Board appoints Philipp Navratil as CEO", url: "https://www.nestle.com/media/pressreleases/allpressreleases/executive-board-changes-september-2025", data: "2025-09-01" }],
  },
  {
    id: "intc-tan-in",
    categoria: "management",
    simbolo: "INTC",
    dataRumor: null,
    dataAnnuncio: "2025-03-12",
    dataEfficacia: "2025-03-18",
    tier: "T2",
    titolo: "Lip-Bu Tan amministratore delegato di Intel",
    persona: "Lip-Bu Tan",
    predecessore: "Pat Gelsinger",
    descrizione: "Predecessore rimosso con il piano di rilancio in affanno; dopo tre mesi di reggenza arriva un esterno.",
    forzato: true,
    successoreEsterno: true,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Intel — Form 8-K", url: "https://www.sec.gov/Archives/edgar/data/50863/000005086325000036/intc-20250310.htm", data: "2025-03-10" }],
  },
  {
    id: "nke-hill-in",
    categoria: "management",
    simbolo: "NKE",
    dataRumor: null,
    dataAnnuncio: "2024-09-19",
    dataEfficacia: "2024-10-14",
    tier: "T3",
    titolo: "Elliott Hill amministratore delegato di Nike",
    persona: "Elliott Hill",
    predecessore: "John Donahoe",
    descrizione: "Uscita presentata come pensionamento ma letta dal mercato come rimozione dopo il calo delle vendite; richiamato un veterano.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Nike announces return of Elliott Hill", url: "https://about.nike.com/en/newsroom/releases/nike-inc-announces-return-of-long-time-nike-veteran-elliott-hill-as-president-and-ceo", data: "2024-09-19" }],
  },
  {
    id: "aapl-ternus-in",
    categoria: "management",
    simbolo: "AAPL",
    dataRumor: null,
    dataAnnuncio: "2026-04-20",
    dataEfficacia: "2026-09-01",
    tier: "T3",
    titolo: "John Ternus amministratore delegato di Apple",
    persona: "John Ternus",
    predecessore: "Tim Cook",
    descrizione: "Successione pianificata: il predecessore passa alla presidenza esecutiva dopo quindici anni.",
    forzato: false,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "alta",
    fonti: [{ titolo: "Tim Cook to become Executive Chairman", url: "https://www.apple.com/newsroom/2026/04/tim-cook-to-become-apple-executive-chairman-john-ternus-to-become-apple-ceo/", data: "2026-04-20" }],
  },
  {
    id: "ldo-mariani-in",
    categoria: "management",
    simbolo: "LDO.MI",
    dataRumor: null,
    dataAnnuncio: "2026-04-09",
    dataEfficacia: "2026-05-08",
    tier: "T3",
    titolo: "Lorenzo Mariani amministratore delegato di Leonardo",
    persona: "Lorenzo Mariani",
    predecessore: "Roberto Cingolani",
    descrizione: "Il governo non ripresenta Cingolani nella lista per il rinnovo del consiglio e designa Mariani, già condirettore generale del gruppo.",
    forzato: true,
    successoreEsterno: false,
    contaminato: false,
    confidenza: "media",
    fonti: [{ titolo: "Il nuovo consiglio di Leonardo nomina Mariani", url: "https://www.analisidifesa.it/2026/05/il-nuovo-cda-di-leonardo-nomina-lorenzo-mariani-amministratore-delegato-e-direttore-generale/", data: "2026-05-08" }],
  },
];
