-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Delivery" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "code" INTEGER NOT NULL,
    "date" DATETIME NOT NULL,
    "serviceTypeId" TEXT NOT NULL,
    "partnerId" TEXT NOT NULL,
    "valetId" TEXT,
    "customerId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'created',
    "paymentStatus" TEXT NOT NULL DEFAULT 'default',
    "deliveryTimeFrom" TEXT,
    "deliveryTimeTo" TEXT,
    "deliveryFlexible" BOOLEAN NOT NULL DEFAULT false,
    "pickupTimeFrom" TEXT,
    "pickupTimeTo" TEXT,
    "pickupFlexible" BOOLEAN NOT NULL DEFAULT false,
    "pickupAddress" TEXT,
    "recipientFirstName" TEXT NOT NULL,
    "recipientLastName" TEXT NOT NULL,
    "recipientAddress" TEXT NOT NULL,
    "recipientIntercom" TEXT,
    "recipientPhone" TEXT,
    "recipientEmail" TEXT,
    "senderFirstName" TEXT,
    "senderLastName" TEXT,
    "senderPhone" TEXT,
    "paymentOnDelivery" BOOLEAN NOT NULL DEFAULT false,
    "paymentAmount" REAL,
    "tryAndReturn" BOOLEAN NOT NULL DEFAULT false,
    "deliveryCodeRequired" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "internalNotes" TEXT,
    "ddtNumber" TEXT,
    "ddtFile" TEXT,
    "distanceKm" REAL,
    "extraKm" REAL NOT NULL DEFAULT 0,
    "extraOutOfCity" BOOLEAN NOT NULL DEFAULT false,
    "deluxyDelivery" BOOLEAN NOT NULL DEFAULT false,
    "valetServiceId" TEXT,
    "billable" BOOLEAN NOT NULL DEFAULT true,
    "payable" BOOLEAN NOT NULL DEFAULT true,
    "price" REAL,
    "additionalPrice" REAL,
    "valetSalary" REAL,
    "valetAdditionalPrice" REAL,
    "isFlexiblePrice" BOOLEAN NOT NULL DEFAULT false,
    "flexiblePrice" TEXT,
    "hours" REAL,
    "personalizeSaleNotes" TEXT,
    "smsPhoneNo" TEXT,
    "smsOnCreated" BOOLEAN NOT NULL DEFAULT false,
    "smsOnDeparted" BOOLEAN NOT NULL DEFAULT false,
    "smsOnArrived" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Delivery_serviceTypeId_fkey" FOREIGN KEY ("serviceTypeId") REFERENCES "ServiceType" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Delivery_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "Partner" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Delivery_valetId_fkey" FOREIGN KEY ("valetId") REFERENCES "Valet" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Delivery_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Delivery" ("additionalPrice", "billable", "code", "createdAt", "customerId", "date", "ddtFile", "ddtNumber", "deliveryCodeRequired", "deliveryTimeFrom", "deliveryTimeTo", "deluxyDelivery", "distanceKm", "extraKm", "extraOutOfCity", "flexiblePrice", "hours", "id", "internalNotes", "isFlexiblePrice", "notes", "partnerId", "payable", "paymentAmount", "paymentOnDelivery", "paymentStatus", "personalizeSaleNotes", "pickupAddress", "pickupFlexible", "pickupTimeFrom", "pickupTimeTo", "price", "recipientAddress", "recipientEmail", "recipientFirstName", "recipientIntercom", "recipientLastName", "recipientPhone", "senderFirstName", "senderLastName", "senderPhone", "serviceTypeId", "smsOnArrived", "smsOnCreated", "smsOnDeparted", "smsPhoneNo", "status", "tryAndReturn", "updatedAt", "valetAdditionalPrice", "valetId", "valetSalary", "valetServiceId") SELECT "additionalPrice", "billable", "code", "createdAt", "customerId", "date", "ddtFile", "ddtNumber", "deliveryCodeRequired", "deliveryTimeFrom", "deliveryTimeTo", "deluxyDelivery", "distanceKm", "extraKm", "extraOutOfCity", "flexiblePrice", "hours", "id", "internalNotes", "isFlexiblePrice", "notes", "partnerId", "payable", "paymentAmount", "paymentOnDelivery", "paymentStatus", "personalizeSaleNotes", "pickupAddress", "pickupFlexible", "pickupTimeFrom", "pickupTimeTo", "price", "recipientAddress", "recipientEmail", "recipientFirstName", "recipientIntercom", "recipientLastName", "recipientPhone", "senderFirstName", "senderLastName", "senderPhone", "serviceTypeId", "smsOnArrived", "smsOnCreated", "smsOnDeparted", "smsPhoneNo", "status", "tryAndReturn", "updatedAt", "valetAdditionalPrice", "valetId", "valetSalary", "valetServiceId" FROM "Delivery";
DROP TABLE "Delivery";
ALTER TABLE "new_Delivery" RENAME TO "Delivery";
CREATE UNIQUE INDEX "Delivery_code_key" ON "Delivery"("code");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
